### ISSUE TITLE
Since the snapshot 22w16b, it seems the launcher do not work properly and causing crashes.

### ISSUE THREAD

**Issue by Wst-04d12** [MrShieh-X/console-minecraft-launcher#10]
Using the following commands to install the version 22w16b, and launch that version normally, you will get the crashes.

java -jar .\CMCL.jar -install 22w16b
> ...
> Copy the native dependency libraries complete
> Install the new version complete

java -jar .\CMCL.jar 22w16b
> Starting game...
> ...
> Game crash possible error: This error may occur because some of the native dependency library are missing or damaged, please re-download native dependency libraries via "-version -n <version name>" to fix this problem.

Following the tip:

java -jar .\CMCL.jar -version -n 22w16b
> ...
> Copy the native dependency libraries complete
> Download native dependency libraries complete

And relaunch the game:
java -jar .\CMCL.jar 22w16b
>Starting game...
[19:04:00] [main/INFO]: Building optimized datafixer
[19:04:01] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
        a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
        b) Add the JAR that contains the shared library to the classpath.
[19:04:01] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[19:04:01] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
Exception in thread "Render thread" [19:04:02] [Render thread/INFO]: [STDERR]: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
[19:04:02] [Render thread/INFO]: [STDERR]:      at ac.a(SourceFile:65)
[19:04:02] [Render thread/INFO]: [STDERR]:      at ecu.a(SourceFile:2289)
[19:04:02] [Render thread/INFO]: [STDERR]:      at ecu.a(SourceFile:2284)
[19:04:02] [Render thread/INFO]: [STDERR]:      at net.minecraft.client.main.Main.main(SourceFile:207)
Game finished

The Error still remains.

After a simple check I found that in folder  \.minecraft\versions\22w16b\natives-windows\
there are only 2 dlls in there.[SAPIWrapper_x64.dll, SAPIWrapper_x86.dll]  

It seems like the launcher failed in copying the dependencies / libraries to the \natives-windows\ and causing the game unable to launch.  

I manually copy the dlls in [previous_version_name]\natives-windows\ to 22w16b\natives-windows\ , and that dosen't work and got a super-long crash report from Minecraft and contains a lot of unrecognizable characters.

I think in this version of minecraft, mojang uses the newer version of  these dependencies, and here is the download log from Mojang official launcher when you are trying to install the 22w16b:

>Downloaded https://libraries.minecraft.net/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar to ...
Downloaded https://libraries.minecraft.net/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar to ...

So I manually download the objects that contain the "natives-windows" and unpack the jars, put the dlls into 22w16b\natives-windows\ , launch the game again using
java -jar .\CMCL.jar 22w16b
and it solved.

The library packs I used are in this zip, and their download URL are in the log from the mojang launcher.
[native-windows.zip](https://github.com/MrShieh-X/console-minecraft-launcher/files/8531052/native-windows.zip)

I can't give a code-level solution or opinion because I don't know Java, but in my coding experience it's pretty easy to solve.

**Comment by MrShieh-X** [comment]
This issue will be resolved in the next version, thank you for your support (btw: your issue is very detailed)
