### ISSUE TITLE
请问可以设置版本隔离吗？

### ISSUE THREAD

**Issue by Jack77793** [MrShieh-X/console-minecraft-launcher#11]
rt.

**Comment by MrShieh-X** [comment]
暂时不可以。

不过，如果该版本认定为是一个整合包，那么它的游戏目录将会在它的版本目录。

如：.minecraft/versions/1.18.2 是一个整合包，那么它的游戏目录将会是 .minecraft/versions/1.18.2，而不是  .minecraft

那么，如何伪装整合包呢？

你可以通过在版本目录（即上文的 .minecraft/versions/1.18.2）新建一个名为 modpack.cfg 或 modpack.json 的空文件，以实现整合包伪装。

不过，该功能在 v1.2 中加入。如果你使用的是旧版 CMCL，请尽快更新。

**Comment by Jack77793** [comment]
好的，谢谢，已成功设置
