### ISSUE TITLE
无法启动安装好的1.19

### ISSUE THREAD

**Issue by funny233-github** [MrShieh-X/console-minecraft-launcher#13]
启动后出现这样的情况:找不到原生依赖库（natives）目录或为空，您需要使用“-version -n <版本名称>”下载原生依赖库文件以启动游戏。按照指示来做后依然不行

**Comment by MrShieh-X** [comment]
这个问题将在下个版本（v1.3）中解决。

不过，你可以使用以下解决方法以解决这个问题。

打开`.minecraft/versions`中你的版本的目录，如`.minecraft/versions/1.19`。然后，在此目录，新建一个名为`natives-windows`的文件夹，然后在这个文件夹内随便新建一个文件或者文件夹。最后，再尝试启动版本，你会发现，启动成功了。
