### ISSUE TITLE
关于版本隔离

### ISSUE THREAD

**Issue by Jack77793** [MrShieh-X/console-minecraft-launcher#16]
rt.
无论是在安装版本时直接安装modloader再设置版本隔离, 还是在安装版本后设置版本隔离再安装modloader, modloader都无法正常生效.
使用[https://github.com/MrShieh-X/console-minecraft-launcher/issues/11#issuecomment-1116786613](https://github.com/MrShieh-X/console-minecraft-launcher/issues/11#issuecomment-1116786613)中的方法也无法使modloader生效.
经测试, 目前已知唯一能使版本隔离与modloader共同生效的方法是导入带有modloader的整合包.
以上.

**Comment by MrShieh-X** [comment]
请问游戏版本、模组加载器及其版本是什么？

**Comment by Jack77793** [comment]
1.18.2, fabric0.14.8, cmcl1.4.1.

**Comment by MrShieh-X** [comment]
我的似乎一切正常。要不你把设置版本隔离的命令发过来看一下？
