### ISSUE TITLE
关于配置文件的路径

### ISSUE THREAD

**Issue by Just-A-Pony** [MrShieh-X/console-minecraft-launcher#18]
目前程序默认会在运行目录下创建cmcl.json  但对于Linux来说  在家目录生成文件到底是不太雅观的
可以增加一个指定配置文件的选项
建议将linux平台的默认行为改为在$HOME/.config目录下创建与读取配置文件，在$HOME/.config/cmcl.json下不存在时  检测$HOME/.cmcl.json和当前运行目录下的cmcl.json 若均不存在 则创建$HOME/.config/cmcl.json 
这样会更方便些

**Comment by MrShieh-X** [comment]
已在v1.8中更改
