### ISSUE TITLE
[Feature]:关于整合包和模组

### ISSUE THREAD

**Issue by CottonCandy2004** [MrShieh-X/console-minecraft-launcher#19]
能否支持安装MCBBS格式整合包？
能否支持检查现有模组的更新与更新模组？

**Comment by MrShieh-X** [comment]
抱歉，这两项功能暂时不支持

**Comment by CottonCandy2004** [comment]
> 抱歉，这两项功能暂时不支持

那请问未来有支持的计划吗？

**Comment by MrShieh-X** [comment]
学业繁忙，考虑一下吧

**Comment by MrShieh-X** [comment]
能告诉我哪里能找到MCBBS格式整合包吗？

**Comment by MrShieh-X** [comment]
v2.0已支持安装MCBBS格式的整合包。至于检查现有模组的更新与更新模组，如果模组是玩家自己下载的，就要在网络查找模组，比较麻烦，可能不会加入。但是如果是从整合包下载到的模组，未来可能会加入。

**Comment by CottonCandy2004** [comment]
感谢！
