### ISSUE TITLE
关于命令提示优化

### ISSUE THREAD

**Issue by serverbread** [MrShieh-X/console-minecraft-launcher#20]
1.我个人认为cmcl是适合开发者，给自己找麻烦的人的，一般这种开源软件使用者都会查看文档，而mc萌新是偏向gui启动器的，肯定不会来选cmcl这种入手门槛高的启动器，因此，当直接执行二进制文件而不加任何参数时应直接打印帮助信息，而非使用提示
2.打印的帮助信息更加格式化，比如短参数后又其对于的长参数：-i:--install
2.mod安装参数冗杂，虽说mod,mod2等方便快捷，但是就是让人非常不舒服...
3.建议方案：
cmcl
         关于   -a[--about]
         帮助   -h[--help]
         列出   -l[--list]
         安装   -i[--install]
                                      launcher /*更新启动器*/
                                      minecraft -v[--version] /*安装新游戏*/ <minecraft_version，example:1.14.514>  (--with [fabric/forge/quilt/liteloader/rift])  /*正式版+modloader>*/
                                                                           <minecraft_version，example:19w198J>  (--with (fabric))  /*快照+(fabric)*/
                                       mod --mc=<id>
         设定 -s[--setting] account chose <id> //选择账号
                                                   add [online/offline/third] <id> //添加
                                                   remove <id> //移除
                                      gamepath choose <id> //选择游戏(.minecraft)路径
                                                        add <String-path> //添加
                                                         remove <id> //移除
                                      source game [office/mcbbs] //游戏源
                                                  resource [Cf/Mf] //资源源
                                       common connections <number>
                                                       ...

**Comment by MrShieh-X** [comment]
全部在v2.0中搞定
