### ISSUE TITLE
能否添加一个通过包管理器进行安装的安装方式

### ISSUE THREAD

**Issue by NobodyHere-rrr** [MrShieh-X/console-minecraft-launcher#23]
如题，希望可以添加一个通过包管理器在 macOS (如homebrew) / Linux (如yay) 上安装cmcl的安装方式，以便于安装与更新cmcl。

**Comment by kikikkiikk** [comment]
目前已经在打包AUR了，应该马上可以在AUR安装到

**Comment by MrShieh-X** [comment]
已上传至AUR，名称为`cmcl`。
homebrew的正在研究

**Comment by MrShieh-X** [comment]
上传到 Homebrew 了，通过以下命令进行安装：</br>
```
brew tap MrShieh-X/brew
brew install cmcl
```
