### ISSUE TITLE
无法正确地检测 JAVA 环境

### ISSUE THREAD

**Issue by StupidQu** [MrShieh-X/console-minecraft-launcher#24]
![image](https://user-images.githubusercontent.com/104199438/215298822-5019fddb-96e1-4d6e-8946-6c557168015f.png)
无法正确检测已设置到环境变量中的 JAVA 运行时。

**Comment by Graetpro** [comment]
这个是exe打包的问题，请自行下载cmcl.jar然后使用`java -jar cmcl.jar`来启动

**Comment by MrShieh-X** [comment]
使用cmcl2.exe，采用了新打包方式
