### ISSUE TITLE
支持&建议

### ISSUE THREAD

**Issue by Jaffe2718** [MrShieh-X/console-minecraft-launcher#25]
用了一下，太喜欢这种操作console的风格了，就像用Windows Powershell一样，不过还是有几点建议：

> 1. 在教程中教用户添加环境变量，直接在Powershell或者cmd里面直接使用，这样方便许多
>   
> 2. -h --help指令的反馈要精简，默认返回常用指令的帮助文档（可以增加--all参数返回全部指令的帮助文档）
>   
> 3. 控制台优化：
>   
> > 显示当前操作的游戏版本，参考Anaconda Prompt (anaconda3)的控制台，会显示当前操作环境的名称，下载和删改资源就默认选择这个游戏版本（可能实现难度较大）
> 
> 4. 导出整合包：
> 
> > 可以添加export指令：
> >  比如：cmcl export <version> <export-path>
> 
> 5. 下载优化：
>   
>   > 1. 下载Minecraft版本时添加重命名版本的选项参数
>   >   
>   > 2. 增加对 resourcepack shaderpack datapack 和地图 的支持
>   >   
>   > 3. 给下载源默认值：
>   >   比如就默认modrinth，或者把默认值添加到全局设置cmcl.json中，避免每次下载都要输入过多的参数
>   >   
>   > 4. 可以从其他网站的url直接下载资源：
>   >   可以添加一个--from-url参数，比如我想直接从Github下载Sodium 0.4.9可以写--from-url=“[https://github.com/CaffeineMC/sodium-fabric/releases/download/mc1.19.3-0.4.9/sodium-fabric-mc1.19.3-0.4.9+build.23.jar”](https://github.com/CaffeineMC/sodium-fabric/releases/download/mc1.19.3-0.4.9/sodium-fabric-mc1.19.3-0.4.9+build.23.jar%E2%80%9D)
>   >   
>   > 5. 下载模组优化：
>   >   自动检索依赖的模组项目，能够读取模组依赖的前置模组的mod id和版本要求，无论是否提供"--from-url"参数都从“--source”参数选择下载源（可能工程量比较大，可以缓一缓）
>   >   
>   > 6. 简化cmcl mod --install参数，并且可以指定模组版本，参考python的 pip工具，比如：cmcl mod --install <mod-id>[==<mod-version>]（可能工程量较大，可以缓一缓）
>   >   
>   
> 6. 资源管理优化：
>   
>   > 1. 管理模组（除了下载以外还可以删除模组，屏蔽模组(直接改扩展名就屏蔽了)）
>   >   
>   > 2. 资源包/光影包/数据包/地图的管理指令
>   >   
>   
> 7. 联机（这个最难搞，不着急）
>   

最后提一点哈，不需要总把新的源码覆盖原本的master分支，不然旧版本的源码就看不到的，可以以版本命名分支并且把最新版分支设为主分支。
en~ 就这么多了，大佬可以参考一下，结合开发的难度和建议的合理性，期待你的更新

**Comment by MrShieh-X** [comment]
1：搞定，在README的疑难解答
2：v2.1，不过没有--all
3：
4：
5.1：本来就有，是-n或--name后面指定
5.2：
5.3：v2.1，首次使用将会询问
5.4：v2.1，不过是`mod --url=<模组地址>`与`modpack --url=<整合包地址>`
5.5：v2.1
5.6：没简化，可以通过`--game-version=<游戏版本>`指定游戏版本，通过`-v, --version=<模组版本>`指定模组或整合包的版本
6：
7：
最后：把新源码覆盖原本master分支这样方便，弄新分支麻烦，作为“测试版”，旧版源码可以在release那里下载

**Comment by Jaffe2718** [comment]
OK
