### ISSUE TITLE
相对路径

### ISSUE THREAD

**Issue by Butterblock233** [MrShieh-X/console-minecraft-launcher#26]
暂不支持相对路径。日常使用的时候会有一点点麻烦(如图)
~顺便问下Discussions去哪了~
![image](https://user-images.githubusercontent.com/97269989/224536116-54e62750-a8c1-447f-8fcc-a2d23ccec294.png)

**Comment by Butterblock233** [comment]
如果可以的话在不填写路径时默认使用当前打开的文件夹的路径，如上图中输入`cmcl -l` 时则列出`D:\Minecraft\StonBlock2\.minecraft`下的版本(慢慢来不着急)

**Comment by MrShieh-X** [comment]
v2.1.2已解决
