### ISSUE TITLE
添加参数使cmcl --list人类可读

### ISSUE THREAD

**Issue by Dage-Hoo** [MrShieh-X/console-minecraft-launcher#28]
如题，有时候看着一长串的列表要找半天，能否添加参数使其人类可读

**Comment by MrShieh-X** [comment]
不是很明白你的意思

**Comment by Dage-Hoo** [comment]
就是希望改成那种类似于一竖排的，比如
1.19
1.20
1.20.1
而非
[1.19,1.20,1.20.1]

**Comment by Xrhhhilo** [comment]
> 就是希望改成那种类似于一竖排的，比如
> 
> ```
> 1.19
> 1.20
> 1.20.1
> ```
> 
> 而非
> 
> ```
> [1.19,1.20,1.20.1]
> ```

那不是太长了吗

**Comment by MrShieh-X** [comment]
> > 就是希望改成那种类似于一竖排的，比如
> > ```
> > 1.19
> > 1.20
> > 1.20.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 而非
> > ```
> > [1.19,1.20,1.20.1]
> > ```
> 
> 那不是太长了吗

我也觉得

**Comment by Dage-Hoo** [comment]
> > > 就是希望改成那种类似于一竖排的，比如
> > > ```
> > > 1.19
> > > 1.20
> > > 1.20.1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 而非
> > > ```
> > > [1.19,1.20,1.20.1]
> > > ```
> > 
> > 
> > 那不是太长了吗
> 
> 我也觉得

![image](https://github.com/MrShieh-X/console-minecraft-launcher/assets/83443827/16a271b6-4e00-42f8-a1bb-9039055f74e8)

有道理，所以我的提议是添加一个参数，不然挤在一起有点难受，因为我习惯的就是竖着的qwq

**Comment by MrShieh-X** [comment]
在v2.2中，打印本地游戏版本、可安装的版本、Forge 版本等都会更直观地显示，且会适应命令行窗口大小，如下图<br/>
![直观显示版本](https://raw.githubusercontent.com/MrShieh-X/console-minecraft-launcher/master/images/visually_display_versions.png "直观显示版本")
