### ISSUE TITLE
需要搜索游戏版本的功能

### ISSUE THREAD

**Issue by zerodegress** [MrShieh-X/console-minecraft-launcher#30]
rt，发现启动器缺失搜索游戏版本的功能
另：启动器的mcbbs api好像有问题，重定向到了BMCLApi

**Comment by MrShieh-X** [comment]
搜索版本？你是说搜索可以安装的版本吗？你可以用`cmcl install -h`的用法二“显示可安装的版本”

**Comment by MrShieh-X** [comment]
刚刚按错了。搜索版本？你是说搜索可以安装的版本吗？你可以用 cmcl install -h 看看用法二“显示可安装的版本”，就是显示可以安装的版本，搜索的功能就没有了。还是你说的是搜索本地版本？

**Comment by zerodegress** [comment]
> 刚刚按错了。搜索版本？你是说搜索可以安装的版本吗？你可以用 cmcl install -h 看看用法二“显示可安装的版本”，就是显示可以安装的版本，搜索的功能就没有了。还是你说的是搜索本地版本？

谢谢，找到了
不过好像mcbbs api出问题了，搜不到1.20

**Comment by MrShieh-X** [comment]
有空我看看

**Comment by MrShieh-X** [comment]
噢，那是因为mcbbs更新有点慢，过几天可能会有的了，你先用着官方下载源吧，下载有点慢也没办法了，等吧
