### ISSUE TITLE
能否添加参数以让启动器启动完毕后自动关闭

### ISSUE THREAD

**Issue by Xrhhhilo** [MrShieh-X/console-minecraft-launcher#32]

**Comment by MrShieh-X** [comment]
你说的关闭指的是在cmd执行完启动命令之后退出CMCL然后可以执行其他命令，还是直接把cmd窗户都关闭？

**Comment by MrShieh-X** [comment]
如果是直接把cmd窗户关闭，这个实现不了，因为涉及到cmd这个单独的进程。还是可以接着执行其他命令那种？那CMCL就可以设计成启动命令执行完之后就退出，可以接着执行其他命令，这个倒可以实现，不知道你说的是哪一种

**Comment by Xrhhhilo** [comment]
> 如果是直接把cmd窗户关闭，这个实现不了，因为涉及到cmd这个单独的进程。还是可以接着执行其他命令那种？那CMCL就可以设计成启动命令执行完之后就退出，可以接着执行其他命令，这个倒可以实现，不知道你说的是哪一种

直接把cmd窗户关闭       很好奇为什么pcl2可以设置 启动后立即关闭呢? 有什么不同你

**Comment by MrShieh-X** [comment]
你是说用pcl2启动完mc后pcl2的窗户就会关闭吗？这是因为这个窗口是属于pcl2的，怎么处理都行，而cmcl和cmd是两个完全没关系的进程，cmd只起到一个交互作用，所以控制不了。通常情况下，你在cmd运行cmcl，按Ctrl+C或关闭cmd是会连游戏也关闭的，可以用`cmcl config exitWithMinecraft false`把这个配置关闭，那么下次启动游戏时就怎么处理cmcl，把cmd窗口关闭，都不会影响到mc的啦，至于自动关闭cmd窗口，真的没办法了
