### ISSUE TITLE
返回模组/整合包图标和数据

### ISSUE THREAD

**Issue by Shapaper** [MrShieh-X/console-minecraft-launcher#33]
能不能加入 -moreinfo参数，返回整合包和模组的图标和下载量数据，<del>比如pcl2可以获取到的那些</del>

**Comment by MrShieh-X** [comment]
图标？显示图标的链接吗？

**Comment by Shapaper** [comment]
是的

**Comment by Shapaper** [comment]
<del>请问您的启动器能作为自制启动器的内核吗</del>

**Comment by MrShieh-X** [comment]
可以，但是必须注明内核是CMCL，作者的名称和B站、GitHub的地址（readme下面有）

**Comment by Shapaper** [comment]
谢谢

**Comment by MrShieh-X** [comment]
在v2.2中，模组与整合包信息中将会带有图标链接与下载量，通过`cmcl mod -h`与`cmcl modpack -h`可获取 --info 的相关用法。
