### ISSUE TITLE
CMCL能成功执行命令，但执行完就闪退

### ISSUE THREAD

**Issue by gyspyw** [MrShieh-X/console-minecraft-launcher#38]
我使用的版本是CMCL2.2.1，电脑为windows
这个版本不能像CMCL2.2中一样，在用户原先使用的CMD窗口中输出命令结果，而是新弹出另一个cmd,可以成功执行命令，但只会显示一瞬间，之后窗口就会关闭
[New Issue · MrShieh-X_console-minecraft-launcher - 个人 - Microsoft​ Edge 2023-08-30 20-49-45.zip](https://github.com/MrShieh-X/console-minecraft-launcher/files/12475741/New.Issue.MrShieh-X_console-minecraft-launcher.-.-.Microsoft.Edge.2023-08-30.20-49-45.zip)

**Comment by gyspyw** [comment]
那如何让cmcl的输出结果在原先的cmd窗口中显示，而非在新的窗口输出结果啊

**Comment by MrShieh-X** [comment]
要不你用回 CMCL v2.2？v2.2.1就修复了几个问题，两个版本差别不大
或者下载cmcl.jar，然后使用java -jar cmcl.jar试一下？
