### ISSUE TITLE
[bug]登录微软账户时浏览器登录不弹出

### ISSUE THREAD

**Issue by BlockyDeer** [MrShieh-X/console-minecraft-launcher#40]
登录微软账户时浏览器登录不弹出，或者说，浏览器毫无反应
### 系统信息
![d86007eac1fef897764bbd0b23ba141a](https://github.com/MrShieh-X/console-minecraft-launcher/assets/102347931/dc8ad76e-491c-499f-a9ec-16fd78eaa5ba)
### 出现bug时的输出
![{2435-x-139915169467}(1)](https://github.com/MrShieh-X/console-minecraft-launcher/assets/102347931/f0903a6a-c221-42bb-8fa9-9d86eb89de9c)
### 浏览器信息
![7ea8dcb5-649c-40b1-ac10-ca9e22821480(1)](https://github.com/MrShieh-X/console-minecraft-launcher/assets/102347931/8903d69e-b1e0-4a15-92e8-10e2d8997ccc)

**Comment by MrShieh-X** [comment]
正常来说可以转跳到浏览器的，可能是对于默认浏览器的设置有问题

**Comment by BlockyDeer** [comment]
能不能让cmcl在登陆微软时试图跳转浏览器的同时在终端显示登录链接和授权码（是这么叫吗），这样跳转失败还能手动登录
现在是根本无法登录

**Comment by MrShieh-X** [comment]
可以，但不是今天，这个功能到时候我再更新，现在先给你临时解决方案：
登录时，手动在浏览器进入这个网站：
```
https://login.live.com/oauth20_authorize.srf?client_id=288ec5dd-6736-4d4b-9b96-30e083a8cad2&response_type=code&scope=XboxLive.signin+offline_access&prompt=select_account&redirect_uri=http%3A%2F%2Flocalhost%3A<端口>%2Fauthentication-response
```
其中，<端口>需要替换成29116到29126之间的11个数字（从29116开始）

**Comment by BlockyDeer** [comment]
11个端口号使用哪一个都可以吗？还是只有一个可以，需要一个一个试？

**Comment by MrShieh-X** [comment]
先试一下29116，不行的话就+1，就是29117，还是不行就29118，这样递归下去。29116通常都可以的

**Comment by BlockyDeer** [comment]
好的

**Comment by MrShieh-X** [comment]
为防止无法跳转至浏览器，在v2.2.2中，每次登录微软账号都会显示链接供用户复制至浏览器打开
