### ISSUE TITLE
[建议]删除MCBBS源

### ISSUE THREAD

**Issue by mibino** [MrShieh-X/console-minecraft-launcher#43]
目前MCBBS已关站，镜像下载源同时不可用，MCBBS源存留没有任何意义，申请删除

**Comment by rubia1120** [comment]
我也是

**Comment by serverbread** [comment]
owner没回复，建议提交pr

**Comment by rubia1120** [comment]
感谢您的来信，祝你有一天成为强打，多多加油！—— UIDrubia

**Comment by rubia1120** [comment]
PR什么鬼？
________________________________
发件人: ***@***.*** ***@***.***> 代表 SB ***@***.***>
发送时间: 2024年6月7日 17:49
收件人: MrShieh-X/console-minecraft-launcher ***@***.***>
抄送: rubia1120 ***@***.***>; Comment ***@***.***>
主题: Re: [MrShieh-X/console-minecraft-launcher] [建议]删除MCBBS源 (Issue #43)


owner没回复，建议提交pr

―

**Comment by MrShieh-X** [comment]
已在v2.2.2中移除
