### ISSUE TITLE
[提问]请问我该如何设置自定义信息？

### ISSUE THREAD

**Issue by Azusa-mikan** [MrShieh-X/console-minecraft-launcher#48]
我在README没有看到相关选项

这个自定义信息会显示在主菜单的左下角和F3的左上角（默认为CMCL）

**Comment by Azusa-mikan** [comment]
查阅了一下HMCL生成的启动脚本
发现 versionType 就是自定义信息

**Comment by Azusa-mikan** [comment]
我使用gameArgs设置了之后，启动游戏发现并未更改，还是CMCL 2.2.2

**Comment by Azusa-mikan** [comment]
[log.txt](https://github.com/user-attachments/files/17001171/log.txt)
![image](https://github.com/user-attachments/assets/3df4aff4-5db6-4bc1-bd92-e61ad0749765)
![image](https://github.com/user-attachments/assets/75fd8cee-307f-472f-b46d-1086a96758b6)

**Comment by MrShieh-X** [comment]
CMCL规定这个不能修改，但是你可以通过命令`cmcl version <版本> --export-script=<bat文件>`或`cmcl version <版本> --export-script-ps=<ps1文件>`导出启动脚本文件，进行修改，再启动游戏。
