### ISSUE TITLE
[New Feature] 是否可以支持本地/在线整合包导入

### ISSUE THREAD

**Issue by Yurzi** [MrShieh-X/console-minecraft-launcher#5]
既然现在已经可以下载模组了想必下一步应该就是支持整合包的导入和安装了awa。

**Comment by Yurzi** [comment]
对于本地整合包的导入的话，其实还有一个问题就是我如何管理多个文件夹目录下的不同游戏版本。
目前1.1版本来说除了修改gameDir之外我没办法在命令行交互式的制定一个目录并选择其中的版本。

**Comment by MrShieh-X** [comment]
下载/安装整合包的功能已在1.2中加入，感谢该建议
管理多游戏目录的功能可能在未来加入
