### ISSUE TITLE
[Problem] 关于外置登录一个账号对应多个角色的问题

### ISSUE THREAD

**Issue by Yurzi** [MrShieh-X/console-minecraft-launcher#6]
## CMCL版本
CMCL 1.1

## 皮肤站版本
Blessing Skin 6.0.0-rc2
理论上支持一个账号多角色的应该都有这个问题

## 问题描述
对于支持一个账号支持多个角色的外置登录皮肤站，在使用cmcl进行外置登陆时无法指定角色而导致失败

## 问题复现
1. 选择一个皮肤站，在同一账号下创建>2的角色数量
2. 在cmcl上使用邮箱或者指定用户名进行外置登录 `cmcl -account -l -a -d "https://<皮肤站域名>/api/yggdrasil"`
3. 报错：`登录失败，请选择一个可用的角色后重试。`

**Comment by MrShieh-X** [comment]
此问题已在1.2中修复，将会询问您要选择哪个角色，感谢对该问题的提出
