### ISSUE TITLE
[New Feature]不同游戏版本的不同JAVA问题

### ISSUE THREAD

**Issue by Yurzi** [MrShieh-X/console-minecraft-launcher#7]
对于某些低版本(或者一些整合包)使用高版本的java可能会造成无法启动的问题。也就说对于一些游戏版本需要指定对应的Java版本。

~*小声BB：我自己都感觉自己事好多，这么多事怎么不自己去提交PR啊*~
作者辛苦了

**Comment by MrShieh-X** [comment]
设置各个游戏版本独立配置的功能已在v1.7加入，可设置独立的 Java 路径
